### ISSUE TITLE
Delete and Put requests return 404

### ISSUE THREAD

**Issue by LloydDeployed** [mentorLAB/blog-mtn#3]
Delete and put requests don't work. Promises are rejected.

--------------Log-------------------
[1] PUT /api/blog/4 404 2.320 ms - 2
[1] DELETE /api/blog/4 404 6.141 ms - 2
-------------------------------------

**Comment by brennongs** [comment]
looks like the route config file is the issue. will look into this with Alan tomorrow.

**Comment by brennongs** [comment]
![image](https://user-images.githubusercontent.com/24623425/31368240-bac61cec-ad39-11e7-9044-cdfd95ac4351.png)

**Comment by brennongs** [comment]
I guess it works now?
![image](https://user-images.githubusercontent.com/24623425/31398165-47ecb0f2-ada5-11e7-8edf-abeb20cbb06d.png)
